apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: disruptive-guestbook
  name: disruptive-guestbook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: disruptive-guestbook
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: disruptive-guestbook
    spec:
      containers:
      - image: hendrikstill/disruptive-guestbook
        imagePullPolicy: Always
        name: disruptive-guestbook
        env:
          - name: SPRING_DATA_MONGODB_HOST
            value: mongo
          - name: ENVIRONMENT_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: ENVIRONMENT_PODNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        envFrom:
          - secretRef:
              name: disruptive-guestbook
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          initialDelaySeconds: 15
          periodSeconds: 3
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
          initialDelaySeconds: 15
          periodSeconds: 3
        resources: {}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: disruptive-guestbook
          matchLabelKeys:
            - pod-template-hash
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: disruptive-guestbook
  name: disruptive-guestbook
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: disruptive-guestbook
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: disruptive-guestbook
spec:
  rules:
    - host: gerry-1.tail812ea.ts.net
      http:
        paths:
          - backend:
              service:
                name: disruptive-guestbook
                port:
                  number: 8080
            path: /
            pathType: Prefix
    - host: guestbook.still.network
      http:
        paths:
          - backend:
              service:
                name: disruptive-guestbook
                port:
                  number: 8080
            path: /
            pathType: Prefix
    - host: demo.still.network
      http:
        paths:
          - backend:
              service:
                name: disruptive-guestbook
                port:
                  number: 8080
            path: /
            pathType: Prefix
status:
  loadBalancer: {}
